/* This file is part of GDB.

   Copyright 2002, 2007 Free Software Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.

   --

   This file was generated by the program igen */

#ifndef ITABLE_H
#define ITABLE_H

typedef enum {
#line 97 "./mips.igen"
  itable_RSVD_SPECIAL,
#line 1756 "./mips.igen"
  itable_ADD_SPECIAL,
#line 1776 "./mips.igen"
  itable_ADDI_NORMAL,
#line 1805 "./mips.igen"
  itable_ADDIU_NORMAL,
#line 1834 "./mips.igen"
  itable_ADDU_SPECIAL,
#line 1861 "./mips.igen"
  itable_AND_SPECIAL,
#line 1881 "./mips.igen"
  itable_ANDI_NORMAL,
#line 1901 "./mips.igen"
  itable_BEQ_NORMAL,
#line 1925 "./mips.igen"
  itable_BEQL_NORMAL,
#line 1950 "./mips.igen"
  itable_BGEZ_REGIMM,
#line 1974 "./mips.igen"
  itable_BGEZAL_REGIMM,
#line 2001 "./mips.igen"
  itable_BGEZALL_REGIMM,
#line 2031 "./mips.igen"
  itable_BGEZL_REGIMM,
#line 2056 "./mips.igen"
  itable_BGTZ_NORMAL,
#line 2080 "./mips.igen"
  itable_BGTZL_NORMAL,
#line 2107 "./mips.igen"
  itable_BLEZ_NORMAL,
#line 2133 "./mips.igen"
  itable_BLEZL_NORMAL,
#line 2158 "./mips.igen"
  itable_BLTZ_REGIMM,
#line 2182 "./mips.igen"
  itable_BLTZAL_REGIMM,
#line 2211 "./mips.igen"
  itable_BLTZALL_REGIMM,
#line 2239 "./mips.igen"
  itable_BLTZL_REGIMM,
#line 2266 "./mips.igen"
  itable_BNE_NORMAL,
#line 2290 "./mips.igen"
  itable_BNEL_NORMAL,
#line 2315 "./mips.igen"
  itable_BREAK_SPECIAL,
#line 2582 "./mips.igen"
  itable_DIV_SPECIAL,
#line 2623 "./mips.igen"
  itable_DIVU_SPECIAL,
#line 3019 "./mips.igen"
  itable_J_NORMAL,
#line 3041 "./mips.igen"
  itable_JAL_NORMAL,
#line 3063 "./mips.igen"
  itable_JALR_SPECIAL,
#line 3095 "./mips.igen"
  itable_JR_SPECIAL,
#line 3225 "./mips.igen"
  itable_LB_NORMAL,
#line 3244 "./mips.igen"
  itable_LBU_NORMAL,
#line 3328 "./mips.igen"
  itable_LH_NORMAL,
#line 3347 "./mips.igen"
  itable_LHU_NORMAL,
#line 3366 "./mips.igen"
  itable_LL_NORMAL,
#line 3398 "./mips.igen"
  itable_LUI_NORMAL,
#line 3417 "./mips.igen"
  itable_LW_NORMAL,
#line 3436 "./mips.igen"
  itable_LWCz_NORMAL,
#line 3455 "./mips.igen"
  itable_LWL_NORMAL,
#line 3474 "./mips.igen"
  itable_LWR_NORMAL,
#line 3558 "./mips.igen"
  itable_MFHI_SPECIAL,
#line 3594 "./mips.igen"
  itable_MFLO_SPECIAL,
#line 3622 "./mips.igen"
  itable_MOVN_SPECIAL,
#line 3637 "./mips.igen"
  itable_MOVZ_SPECIAL,
#line 3694 "./mips.igen"
  itable_MTHI_SPECIAL,
#line 3722 "./mips.igen"
  itable_MTLO_SPECIAL,
#line 3780 "./mips.igen"
  itable_MULT_SPECIAL,
#line 3832 "./mips.igen"
  itable_MULTU_SPECIAL,
#line 3875 "./mips.igen"
  itable_NOR_SPECIAL,
#line 3901 "./mips.igen"
  itable_OR_SPECIAL,
#line 3928 "./mips.igen"
  itable_ORI_NORMAL,
#line 3947 "./mips.igen"
  itable_PREF_NORMAL,
#line 4079 "./mips.igen"
  itable_SB_NORMAL,
#line 4098 "./mips.igen"
  itable_SC_NORMAL,
#line 4193 "./mips.igen"
  itable_SH_NORMAL,
#line 4220 "./mips.igen"
  itable_SLLa_SPECIAL,
#line 4263 "./mips.igen"
  itable_SLLV_SPECIAL,
#line 4289 "./mips.igen"
  itable_SLT_SPECIAL,
#line 4315 "./mips.igen"
  itable_SLTI_NORMAL,
#line 4341 "./mips.igen"
  itable_SLTIU_NORMAL,
#line 4368 "./mips.igen"
  itable_SLTU_SPECIAL,
#line 4397 "./mips.igen"
  itable_SRA_SPECIAL,
#line 4428 "./mips.igen"
  itable_SRAV_SPECIAL,
#line 4458 "./mips.igen"
  itable_SRL_SPECIAL,
#line 4488 "./mips.igen"
  itable_SRLV_SPECIAL,
#line 4507 "./mips.igen"
  itable_SUB_SPECIAL,
#line 4535 "./mips.igen"
  itable_SUBU_SPECIAL,
#line 4554 "./mips.igen"
  itable_SW_NORMAL,
#line 4573 "./mips.igen"
  itable_SWCz_NORMAL,
#line 4592 "./mips.igen"
  itable_SWL_NORMAL,
#line 4611 "./mips.igen"
  itable_SWR_NORMAL,
#line 4630 "./mips.igen"
  itable_SYNC_SPECIAL,
#line 4649 "./mips.igen"
  itable_SYSCALL_SPECIAL,
#line 4668 "./mips.igen"
  itable_TEQ_SPECIAL,
#line 4685 "./mips.igen"
  itable_TEQI_REGIMM,
#line 4702 "./mips.igen"
  itable_TGE_SPECIAL,
#line 4719 "./mips.igen"
  itable_TGEI_REGIMM,
#line 4736 "./mips.igen"
  itable_TGEIU_REGIMM,
#line 4753 "./mips.igen"
  itable_TGEU_SPECIAL,
#line 4770 "./mips.igen"
  itable_TLT_SPECIAL,
#line 4787 "./mips.igen"
  itable_TLTI_REGIMM,
#line 4804 "./mips.igen"
  itable_TLTIU_REGIMM,
#line 4821 "./mips.igen"
  itable_TLTU_SPECIAL,
#line 4838 "./mips.igen"
  itable_TNE_SPECIAL,
#line 4855 "./mips.igen"
  itable_TNEI_REGIMM,
#line 4879 "./mips.igen"
  itable_XOR_SPECIAL,
#line 4905 "./mips.igen"
  itable_XORI_NORMAL,
#line 5121 "./mips.igen"
  itable_ABS_fmt_COP1,
#line 5141 "./mips.igen"
  itable_ADD_fmt_COP1,
#line 5201 "./mips.igen"
  itable_BC1b_COP1S,
#line 5239 "./mips.igen"
  itable_C_cond_fmtb_COP1,
#line 5256 "./mips.igen"
  itable_CEIL_L_fmt_COP1,
#line 5272 "./mips.igen"
  itable_CEIL_W_COP1,
#line 5304 "./mips.igen"
  itable_CFC1b_COP1,
#line 5345 "./mips.igen"
  itable_CTC1b_COP1,
#line 5374 "./mips.igen"
  itable_CVT_D_fmt_COP1,
#line 5393 "./mips.igen"
  itable_CVT_L_fmt_COP1,
#line 5423 "./mips.igen"
  itable_CVT_S_fmt_COP1,
#line 5464 "./mips.igen"
  itable_CVT_W_fmt_COP1,
#line 5483 "./mips.igen"
  itable_DIV_fmt_COP1,
#line 5570 "./mips.igen"
  itable_FLOOR_L_fmt_COP1,
#line 5586 "./mips.igen"
  itable_FLOOR_W_fmt_COP1,
#line 5615 "./mips.igen"
  itable_LDC1b_COP1,
#line 5674 "./mips.igen"
  itable_LWC1_COP1,
#line 5693 "./mips.igen"
  itable_LWXC1_COP1X,
#line 5707 "./mips.igen"
  itable_MADD_fmt_COP1X,
#line 5733 "./mips.igen"
  itable_MFC1b_COP1,
#line 5749 "./mips.igen"
  itable_MOV_fmt_COP1,
#line 5770 "./mips.igen"
  itable_MOVtf_SPECIAL,
#line 5786 "./mips.igen"
  itable_MOVtf_fmt_COP1,
#line 5800 "./mips.igen"
  itable_MOVN_fmt_COP1,
#line 5821 "./mips.igen"
  itable_MOVZ_fmt_COP1,
#line 5835 "./mips.igen"
  itable_MSUB_fmt_COP1X,
#line 5862 "./mips.igen"
  itable_MTC1b_COP1,
#line 5878 "./mips.igen"
  itable_MUL_fmt_COP1,
#line 5897 "./mips.igen"
  itable_NEG_fmt_COP1,
#line 5916 "./mips.igen"
  itable_NMADD_fmt_COP1X,
#line 5929 "./mips.igen"
  itable_NMSUB_fmt_COP1X,
#line 5964 "./mips.igen"
  itable_PREFX_COP1X,
#line 5999 "./mips.igen"
  itable_RECIP_fmt_COP1,
#line 6012 "./mips.igen"
  itable_ROUND_L_fmt_COP1,
#line 6028 "./mips.igen"
  itable_ROUND_W_fmt_COP1,
#line 6046 "./mips.igen"
  itable_RSQRT_fmt_COP1,
#line 6069 "./mips.igen"
  itable_SDC1b_COP1,
#line 6128 "./mips.igen"
  itable_SQRT_fmt_COP1,
#line 6146 "./mips.igen"
  itable_SUB_fmt_COP1,
#line 6166 "./mips.igen"
  itable_SWC1_COP1,
#line 6185 "./mips.igen"
  itable_SWXC1_COP1X,
#line 6198 "./mips.igen"
  itable_TRUNC_L_fmt_COP1,
#line 6214 "./mips.igen"
  itable_TRUNC_W_COP1,
#line 6239 "./mips.igen"
  itable_BC0F_COP0,
#line 6262 "./mips.igen"
  itable_BC0FL_COP0,
#line 6277 "./mips.igen"
  itable_BC0T_COP0,
#line 6291 "./mips.igen"
  itable_BC0TL_COP0,
#line 6306 "./mips.igen"
  itable_CACHE_NORMAL,
#line 6355 "./mips.igen"
  itable_ERET_COP0,
#line 6382 "./mips.igen"
  itable_MFC0_COP0,
#line 6402 "./mips.igen"
  itable_MTC0_COP0,
#line 6421 "./mips.igen"
  itable_RFE_COP0,
#line 6436 "./mips.igen"
  itable_COPz_NORMAL,
#line 6455 "./mips.igen"
  itable_TLBP_COP0,
#line 6470 "./mips.igen"
  itable_TLBR_COP0,
#line 6485 "./mips.igen"
  itable_TLBWI_COP0,
#line 6500 "./mips.igen"
  itable_TLBWR_COP0,
  nr_itable_entries,
} itable_index;

typedef enum {
  itable_flag_32,
  itable_flag_f,
  nr_itable_flags,
} itable_flags;
extern const char *itable_flag_names[];

typedef enum {
  nr_itable_options,
} itable_options;
extern const char *itable_option_names[];

typedef enum {
  itable_processor_dsp,
  itable_processor_dsp2,
  itable_processor_mdmx,
  itable_processor_micromips32,
  itable_processor_micromips64,
  itable_processor_micromipsdsp,
  itable_processor_mips16,
  itable_processor_mips16e,
  itable_processor_mips32,
  itable_processor_mips32r2,
  itable_processor_mips3d,
  itable_processor_mips64,
  itable_processor_mips64r2,
  itable_processor_mipsI,
  itable_processor_mipsII,
  itable_processor_mipsIII,
  itable_processor_mipsIV,
  itable_processor_mipsV,
  itable_processor_r3900,
  itable_processor_sb1,
  itable_processor_smartmips,
  itable_processor_vr4100,
  itable_processor_vr4120,
  itable_processor_vr5000,
  itable_processor_vr5400,
  itable_processor_vr5500,
  nr_itable_processors,
} itable_processors;
extern const char *itable_processor_names[];

typedef struct _itable_instruction_info {
  itable_index nr;
  char *format;
  char *form;
  char *flags;
  char flag[nr_itable_flags + 1];
  char *options;
  char option[nr_itable_options + 1];
  char *processors;
  char processor[nr_itable_processors + 1];
  char *name;
  char *file;
  int line_nr;
} itable_info;

extern itable_info itable[nr_itable_entries];

enum {
  sizeof_itable_form = 8,
  sizeof_itable_name = 12,
  sizeof_itable_file = 10,
};

#endif /* _ITABLE_H_*/
